project:
  type: website
  output-dir: docs

website:
  # title: "TF"
  site-url: "https://feracotommaso.github.io/"
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - text: "home"
        href: index.qmd
      - text: "resources"
        href: open-resources.qmd
      # - text: "courses"
      #   href: courses.qmd
      - text: "slides"
        href: slides.qmd
      - text: "projects"
        href: projects.qmd
      - text: "posts"
        href: posts.qmd
      # - text: "contact"
      #   href: contact.qmd

format:
  html: 
    include-in-header:
       text: |
         <link rel="shortcut icon" href="img/favicon.png"/>
    theme:
      light: yeti
    fontsize: 1.2em
    linestretch: 1.7
    css: styles.css
    toc: true
    smooth-scroll: true

